version: 2

project_name: midiwav

before:
  hooks:
    - go mod tidy

builds:
  - id: midiwav
    main: .
    binary: midiwav
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      # Windows arm64 が不要なら落とす
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "checksums.txt"

release:
  prerelease: true

changelog:
  use: github
